name: Template Cleanup
on:
  push:
    branches: [ main ]
jobs:
  template-cleanup:
    name: Template Cleanup
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'laravel-package-template'
    permissions:
      contents: write
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Cleanup
        run: |
          NAME="${GITHUB_REPOSITORY##*/}"
          KEBAB=$(echo $NAME | tr -s -c '[:alpha:][:cntrl:]' ' ' | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
          STUDLY=$(echo $NAME | tr -s -c '[:alpha:][:cntrl:]' ' ' | tr '[:upper:]' '[:lower:]' | awk '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) tolower(substr($i,2))}print}')
          
          echo "Kebab case: ${KEBAB}"
          echo "Studly case: ${STUDLY}"

          # Replace placeholder names
          find src -type f -exec sed -i "s/laravel-package-template/$KEBAB/g" {} +
          find src -type f -exec sed -i "s/LaravelPackageTemplate/$STUDLY/g" {} +
          
          # Rename files
          mv .idea/laravel-package-template.iml .idea/$KEBAB.iml

          # Cleanup
          rm -f .github/workflows/template-cleanup.yml
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Template cleanup"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
